version: '3.5'

services:
  pismo-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pismo-api-image
    container_name: pismo-api
    tty: true
    working_dir: /var/www/html
    networks:
      - pismo_network
    volumes:
      - .:/var/www/html
    ports:
      - 8084:8084

# networks
networks:
  pismo_network:
    name: pismo
    driver: bridge